import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { getPublicProfile, sendPublicMessage } from "../api/publicApi";

export default function PublicProfilePage() {
  const { publicId } = useParams(); const [profile,setProfile]=useState(null); const [messages,setMessages]=useState([]); const [input,setInput]=useState(""); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{getPublicProfile(publicId).then((data)=>{setProfile(data);setMessages([{role:"assistant",content:data.initial_message}]);}).catch((err)=>setError(err.response?.data?.detail||"Profil introuvable.")).finally(()=>setLoading(false));},[publicId]);
  const submit=async(event)=>{event.preventDefault();const text=input.trim();if(!text||sending)return;const next=[...messages,{role:"user",content:text}];setMessages(next);setInput("");setSending(true);try{const result=await sendPublicMessage(publicId,text,next.slice(-6));setMessages([...next,{role:"assistant",content:result.reply}]);}catch{setMessages([...next,{role:"assistant",content:"Je ne peux pas répondre maintenant. Restez calme et utilisez les informations affichées."}]);}finally{setSending(false);}};
  if(loading)return <main className="public-help"><div className="public-loading">Chargement de la fiche d’aide…</div></main>;
  if(error)return <main className="public-help"><div className="public-loading error">{error}</div></main>;
  return <main className="public-help"><header className="public-header"><div className="brand">Bridge<span>.</span></div><span>Fiche d’aide publique</span></header><div className="public-grid"><section className="emergency-summary"><p className="eyebrow">Comment aider</p><h1>{profile.name} peut avoir besoin de vous</h1><p className="public-intro">Restez calme, parlez doucement et respectez les messages ci-dessous.</p><h2>États et messages</h2>{profile.cards.length===0?<div className="public-empty">Aucune carte publique enregistrée.</div>:profile.cards.map((card,index)=><article className="public-need" key={index}><span>{card.state}</span><p>{card.message}</p></article>)}<h2>Contacts de confiance</h2>{profile.contacts.length===0?<div className="public-empty">Aucun numéro disponible.</div>:profile.contacts.map((contact,index)=><a className="phone-contact" href={`tel:${contact.phone}`} key={index}><div className="avatar">{contact.name.charAt(0).toUpperCase()}</div><div><strong>{contact.name}</strong><span>{contact.phone}</span></div><b>Appeler</b></a>)}</section><section className="public-chat"><div className="chat-heading"><div className="ai-dot"></div><div><strong>Assistant Bridge</strong><span>Propulsé par Gemma 4</span></div></div><div className="chat-messages">{messages.map((message,index)=><div className={`chat-bubble ${message.role}`} key={index}>{message.content}</div>)}{sending&&<div className="chat-bubble assistant typing">Gemma prépare une réponse…</div>}</div><form className="chat-input" onSubmit={submit}><input value={input} onChange={e=>setInput(e.target.value)} maxLength="500" placeholder="Comment puis-je aider ?"/><button disabled={sending||!input.trim()}>Envoyer</button></form></section></div></main>;
}
